[package]
name = "shinra-engine"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
wgpu = "27"
pollster = "0.3"
bytemuck = { version = "1", features = ["derive"] }
glam = "0.28"
tobj = "4"
image = "0.25"
viuer = "0.11"
crossterm = "0.27"
anyhow = "1"
gametok-abi = { path = "../abi" }
hecs = "0.10"
scene-format = { package = "scene", path = "../scene" }
libloading = "0.8"
ron = "0.10"

[dev-dependencies]
tempfile = "3"
