[package]
name = "shinra-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "shinra"
path = "src/main.rs"

[dependencies]
anyhow = "1"

[dev-dependencies]
shinra-engine = { path = "../engine" }
gametok-abi   = { path = "../abi" }
scene         = { path = "../scene" }
ron           = "0.10"
serde         = { version = "1", features = ["derive"] }
