//! Turning a source tree into `.so` files.
//!
//! Each module is one `rustc` invocation. There is no `Cargo.toml` per module
//! and no build script, because a module is a single file plus whatever it
//! pulls in — making it a cargo package would add a manifest that could
//! disagree with the tree.

use crate::discover::{BundleSrc, Category, ModuleSrc};
use anyhow::{anyhow, bail, Context, Result};
use std::path::{Path, PathBuf};
use std::process::Command;

/// Where `libse.rlib` and its dependencies live.
pub struct Engine {
    pub root: PathBuf,
    pub deps: PathBuf,
    pub se_rlib: PathBuf,
}

impl Engine {
    /// `$SHINRA_ENGINE`, else the workspace this binary was built from.
    pub fn find(profile: &str) -> Result<Engine> {
        let root = match std::env::var_os("SHINRA_ENGINE") {
            Some(p) => PathBuf::from(p),
            None => {
                let exe = std::env::current_exe()?;
                exe.ancestors()
                    .find(|a| a.join("crates/se/Cargo.toml").is_file())
                    .map(|a| a.to_path_buf())
                    .ok_or_else(|| {
                        anyhow!("cannot find the engine; set SHINRA_ENGINE to its checkout")
                    })?
            }
        };
        let out = root.join("target").join(profile);
        Ok(Engine { se_rlib: out.join("libse.rlib"), deps: out.join("deps"), root })
    }

    /// `se` is what modules compile against, so it has to exist before they do.
    pub fn ensure_se(&self, profile: &str) -> Result<()> {
        let mut c = Command::new("cargo");
        c.arg("build").arg("-p").arg("se");
        if profile == "release" {
            c.arg("--release");
        }
        c.arg("--manifest-path").arg(self.root.join("Cargo.toml"));
        let st = c.status().context("running cargo build -p se")?;
        if !st.success() {
            bail!("building `se` failed");
        }
        if !self.se_rlib.is_file() {
            bail!("expected {} after building `se`", self.se_rlib.display());
        }
        Ok(())
    }
}

/// The generated crate root for one module.
///
/// `#[path]` on an *inline* module sets the directory its children are looked
/// up in. That single detail is what lets the design's layout rule hold with
/// no source-tree pollution: `graph1.rs` is then found by name, so its own
/// `mod common;` lands in `render/graph1/` — private to it — while a shared
/// folder is declared here and reached as `crate::render::common`.
fn root_for(m: &ModuleSrc, cat: &Category) -> String {
    // Absolute: `#[path]` resolves against the file it appears in, and this
    // root lives in the build directory, not beside the sources.
    let dir = abs(&cat.dir);
    let mut s = String::new();
    s.push_str("// generated by shinra — do not edit\n");
    s.push_str(&format!("#[path = {:?}]\n", dir));
    s.push_str(&format!("mod {} {{\n", cat.name));
    for sh in &cat.shared {
        s.push_str(&format!("    pub mod {sh};\n"));
    }
    s.push_str(&format!("    pub mod {};\n", m.name));
    s.push_str("}\n");
    s
}

/// `bundle.so` is the exception: two files, one library, one contract.
fn bundle_root(src: &BundleSrc) -> String {
    let dir = abs(&src.root.join("bundle"));
    format!(
        "// generated by shinra — do not edit\n\
         // `data.rs` exists to be compiled into every other module too, so an\n\
         // item only `process/` or `game/` uses is not dead here.\n\
         #![allow(dead_code)]\n\
         se::abi_version!();\n\
         #[path = {dir:?}]\n\
         mod bundle {{\n    \
             pub mod data;\n    \
             pub mod buffer;\n\
         }}\n"
    )
}

/// Absolute, symlinks resolved — anything less breaks `#[path]` from a
/// generated root that does not sit beside the sources.
fn abs(p: &Path) -> PathBuf {
    std::fs::canonicalize(p).unwrap_or_else(|_| p.to_path_buf())
}

pub struct Built {
    pub modules: Vec<String>,
}

fn rustc(engine: &Engine, profile: &str) -> Command {
    let mut c = Command::new("rustc");
    c.arg("--edition").arg("2021");
    c.arg("-L").arg(format!("dependency={}", engine.deps.display()));
    c.arg("--extern").arg(format!("se={}", engine.se_rlib.display()));
    if profile == "release" {
        c.arg("-C").arg("opt-level=3");
    } else {
        c.arg("-C").arg("debuginfo=1");
    }
    // Modules are dlopen'd; each needs its own copy of what it uses.
    c.arg("-C").arg("prefer-dynamic=no");
    c
}

fn run(mut c: Command, what: &str) -> Result<()> {
    let out = c.output().with_context(|| format!("running rustc for {what}"))?;
    if !out.status.success() {
        let err = String::from_utf8_lossy(&out.stderr);
        bail!("{what} failed to build:\n{err}");
    }
    let err = String::from_utf8_lossy(&out.stderr);
    if !err.trim().is_empty() {
        eprint!("{err}");
    }
    Ok(())
}

/// Build every module of one bundle into `out`.
pub fn build(src: &BundleSrc, out: &Path, engine: &Engine, profile: &str) -> Result<Built> {
    std::fs::create_dir_all(out)?;
    let gen = out.join(".gen");
    std::fs::create_dir_all(&gen)?;

    // 1. The contract, as a library the rest of the bundle compiles against.
    //    Sharing the source is what makes "obeys the bundle contract" a
    //    compile-time fact for a module rather than a hope.
    let data_rlib = out.join("libdata.rlib");
    let mut c = rustc(engine, profile);
    c.arg("--crate-type").arg("rlib").arg("--crate-name").arg("data");
    c.arg("-o").arg(&data_rlib).arg(&src.data);
    run(c, "bundle/data.rs (as a library)")?;

    // 2. bundle.so itself: data.rs + buffer.rs, one image, one contract.
    let root = gen.join("bundle_root.rs");
    std::fs::write(&root, bundle_root(src))?;
    let mut c = rustc(engine, profile);
    c.arg("--crate-type").arg("cdylib").arg("--crate-name").arg("bundle");
    c.arg("-o").arg(out.join("bundle.so")).arg(&root);
    run(c, "bundle.so")?;

    // 3. Everything else, each against the contract.
    let mut names = vec!["bundle".to_string()];
    for cat in &src.categories {
        if cat.modules.is_empty() {
            continue;
        }
        let cdir = out.join(&cat.name);
        std::fs::create_dir_all(&cdir)?;
        for m in &cat.modules {
            let root = gen.join(format!("{}_{}_root.rs", cat.name, m.name));
            std::fs::write(&root, root_for(m, cat))?;
            let mut c = rustc(engine, profile);
            c.arg("--crate-type").arg("cdylib").arg("--crate-name").arg(&m.name);
            c.arg("--extern").arg(format!("data={}", data_rlib.display()));
            c.arg("-o").arg(cdir.join(format!("{}.so", m.name))).arg(&root);
            run(c, &format!("{}/{}.rs", cat.name, m.name))?;
            names.push(format!("{}/{}", cat.name, m.name));
        }
    }

    Ok(Built { modules: names })
}

/// Rebuild only the modules whose sources changed. Used by the run loop's
/// hot reload, where rebuilding everything would stall the frame.
pub fn build_changed(
    src: &BundleSrc,
    out: &Path,
    engine: &Engine,
    profile: &str,
) -> Result<Vec<String>> {
    let mut stale = Vec::new();
    for cat in &src.categories {
        for m in &cat.modules {
            let so = out.join(&cat.name).join(format!("{}.so", m.name));
            if newer(&m.file, &so)? || category_newer(cat, &so)? {
                stale.push(m.clone());
            }
        }
    }
    let bundle_stale = newer(&src.data, &out.join("bundle.so"))?
        || newer(&src.buffer, &out.join("bundle.so"))?;

    if bundle_stale {
        // A changed contract is not a reload. Rebuild the whole set.
        build(src, out, engine, profile)?;
        return Ok(vec!["bundle".into()]);
    }

    let mut done = Vec::new();
    let gen = out.join(".gen");
    let data_rlib = out.join("libdata.rlib");
    for m in &stale {
        let cat = src.category(&m.category).expect("category exists");
        let root = gen.join(format!("{}_{}_root.rs", cat.name, m.name));
        std::fs::write(&root, root_for(m, cat))?;
        let mut c = rustc(engine, profile);
        c.arg("--crate-type").arg("cdylib").arg("--crate-name").arg(&m.name);
        c.arg("--extern").arg(format!("data={}", data_rlib.display()));
        c.arg("-o")
            .arg(out.join(&cat.name).join(format!("{}.so", m.name)))
            .arg(&root);
        run(c, &format!("{}/{}.rs", cat.name, m.name))?;
        done.push(m.name.clone());
    }
    Ok(done)
}

fn newer(src: &Path, out: &Path) -> Result<bool> {
    let Ok(o) = std::fs::metadata(out).and_then(|m| m.modified()) else {
        return Ok(true);
    };
    let s = std::fs::metadata(src)?.modified()?;
    Ok(s > o)
}

/// Anything deeper than depth 1 is a source file inside a module — including
/// `.wgsl`, which `include_str!` pulls in without rustc ever being re-run on
/// our behalf. So a module is stale if *any* non-module file in its category
/// moved: its own private folder, or the category's shared one.
///
/// This over-rebuilds — touching `render/solid/fs.wgsl` also rebuilds
/// `ghost.so`. That is the right way round: a rebuild costs a second, and a
/// missed one serves a stale shader that looks like a rendering bug.
fn category_newer(cat: &Category, so: &Path) -> Result<bool> {
    for f in crate::discover::walkdir(&cat.dir)? {
        // Depth-1 `.rs` files are modules in their own right, not sources of
        // this one.
        if f.parent() == Some(cat.dir.as_path()) && f.extension().is_some_and(|e| e == "rs") {
            continue;
        }
        if newer(&f, so)? {
            return Ok(true);
        }
    }
    Ok(false)
}
