//! Emits the crate that turns a game folder into a loadable module.
//!
//! A game folder holds only `scene.ron`, `input.tres.ron` and `.hom` files. The
//! ABI implementation, the World construction and the system dispatch are all
//! derived from what the `.hom` files declared, so a game never hand-writes
//! engine glue.

use crate::discover::{Module, Param};

/// One shared `engine` module means one `Transform` type for the whole crate,
/// which is why the modules are compiled with `--extern engine`.
pub fn cargo_toml(game: &str, engine_root: &str) -> String {
    format!(
        r#"# Generated by `shinra build`. Do not edit; regenerate instead.
[package]
name = "{game}"
version = "0.1.0"
edition = "2021"

[lib]
name = "{game}"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
shinra-engine = {{ path = "{engine_root}/engine" }}
scene         = {{ path = "{engine_root}/scene" }}
gametok-abi   = {{ path = "{engine_root}/abi" }}
hecs          = "0.10"
ron           = "0.10"
serde         = {{ version = "1", features = ["derive"] }}
"#
    )
}

fn component_arms(modules: &[Module]) -> String {
    let mut out = String::new();
    for m in modules {
        for c in &m.components {
            out.push_str(&format!(
                "            \"{c}\" => insert_from(&mut world, e, parse::<{module}::{c}>(value)),\n",
                module = m.name
            ));
        }
    }
    out
}

/// Which module declares a component, so a system's query can name its type.
fn owner_of<'a>(modules: &'a [Module], ty: &str) -> Option<&'a str> {
    modules
        .iter()
        .find(|m| m.components.iter().any(|c| c == ty))
        .map(|m| m.name.as_str())
}

fn system_block(m: &Module, sys: &crate::discover::System, modules: &[Module]) -> String {
    let comps: Vec<&Param> = sys
        .params
        .iter()
        .filter(|p| matches!(p, Param::Component { .. }))
        .collect();
    let wants_transform = sys.params.iter().any(|p| matches!(p, Param::Transform));

    // `&NodeIdx` is always in the query: a mutated component has to be written
    // back into the scene node it came from, or the host never sees it.
    let mut query_parts: Vec<String> = vec!["&NodeIdx".to_string()];
    for p in &comps {
        if let Param::Component { ty, by_ref } = p {
            let owner = owner_of(modules, ty).unwrap_or(&m.name);
            query_parts.push(if *by_ref {
                format!("&mut {owner}::{ty}")
            } else {
                format!("&{owner}::{ty}")
            });
        }
    }
    let query = format!("({})", query_parts.join(", "));

    let mut binds: Vec<String> = vec!["idx".to_string()];
    for (i, _) in comps.iter().enumerate() {
        binds.push(format!("c{i}"));
    }
    let bind_pat = format!("({})", binds.join(", "));

    // Call arguments, in declared parameter order.
    let mut ci = 0usize;
    let mut args: Vec<String> = Vec::new();
    for p in &sys.params {
        match p {
            Param::Transform => args.push("&mut node.transform".to_string()),
            Param::Dt => args.push("dt".to_string()),
            Param::Component { by_ref, .. } => {
                args.push(if *by_ref {
                    format!("c{ci}")
                } else {
                    format!("c{ci}.clone()")
                });
                ci += 1;
            }
        }
    }
    let call = format!("{}::{}({})", m.name, sys.name, args.join(", "));

    // The script indexes `[f32; 3]` directly, so the node's own transform is
    // handed over with no conversion.
    let _ = wants_transform;

    // Write mutated components back, so scene.ron reflects live state and the
    // host can read it.
    let mut write_back = String::new();
    let mut ci = 0usize;
    for p in &comps {
        if let Param::Component { ty, by_ref } = p {
            if *by_ref {
                write_back.push_str(&format!(
                    "        write_back(node, \"{ty}\", &*c{ci});\n"
                ));
            }
            ci += 1;
        }
    }

    format!(
        r#"    // {module}.hom
    for (_e, {bind_pat}) in world.query::<{query}>().iter() {{
        let node = &mut scene.nodes[idx.0];
        {call};
{write_back}    }}
"#,
        module = m.name
    )
}

fn overlap_blocks(modules: &[Module]) -> String {
    let mut pairs: Vec<(String, String)> = Vec::new();
    for m in modules {
        for p in &m.overlap_pairs {
            if !pairs.contains(p) {
                pairs.push(p.clone());
            }
        }
    }
    if pairs.is_empty() {
        return "    Vec::new()\n".to_string();
    }
    let mut out = String::from("    let mut pairs = Vec::new();\n");
    for (a, b) in pairs {
        let (oa, ob) = (
            owner_of(modules, &a).unwrap_or(""),
            owner_of(modules, &b).unwrap_or(""),
        );
        if oa.is_empty() || ob.is_empty() {
            continue;
        }
        out.push_str(&format!(
            r#"    for (ea, ca) in game.world.query::<&scene::Collider>().iter() {{
        if game.world.get::<&{oa}::{a}>(ea).is_err() {{ continue }}
        let Ok(ia) = game.world.get::<&NodeIdx>(ea) else {{ continue }};
        let ta = game.scene.nodes[ia.0].transform;
        for (eb, cb) in game.world.query::<&scene::Collider>().iter() {{
            if ea == eb {{ continue }}
            if game.world.get::<&{ob}::{b}>(eb).is_err() {{ continue }}
            let Ok(ib) = game.world.get::<&NodeIdx>(eb) else {{ continue }};
            let tb = game.scene.nodes[ib.0].transform;
            if overlaps((&ta, &ca), (&tb, &cb)) {{
                pairs.push(("{a}".to_string(), "{b}".to_string()));
            }}
        }}
    }}
"#
        ));
    }
    out.push_str("    pairs\n");
    out
}

pub fn lib_rs(game: &str, modules: &[Module]) -> String {
    let mod_decls: String = modules
        .iter()
        .map(|m| {
            format!(
                "#[allow(unused_variables, unused_mut, dead_code, unused_imports, unused_macros, non_snake_case)]\nmod {};\n",
                m.name
            )
        })
        .collect();

    let systems: String = modules
        .iter()
        .flat_map(|m| m.systems.iter().map(move |s| system_block(m, s, modules)))
        .collect();

    let component_arms = component_arms(modules);
    let overlap_blocks = overlap_blocks(modules);

    format!(
        r#"//! Generated by `shinra build` for the game `{game}`. Do not edit.
//!
//! The engine derives this from what the game's `.hom` files declared: each
//! `pub struct` is a component, and each `*_system` function's parameter list
//! is its query.

use std::collections::BTreeMap;
use std::sync::Mutex;

use gametok_abi::{{keys, KeyFrame}};
use shinra_engine::script;

/// The Homun runtime, once. `#[macro_use]` so its macros reach the modules
/// below, which import its traits via `--runtime-path super::runtime`.
#[macro_use]
#[allow(unused_variables, unused_mut, dead_code, unused_imports, unused_macros, non_snake_case)]
mod runtime {{
    include!("runtime.rs");
}}

/// The engine's Homun shim, once, so every module shares one `Transform`.
#[allow(unused_variables, unused_mut, dead_code, unused_imports, non_snake_case)]
mod engine;

{mod_decls}
const ACTION_MAP: &str = include_str!("input.tres.ron");

#[derive(serde::Deserialize)]
struct ActionMap {{
    actions: BTreeMap<String, Vec<String>>,
}}

/// Links an entity back to the scene node it renders as.
struct NodeIdx(usize);

struct Game {{
    scene: scene::Scene,
    initial: scene::Scene,
    world: hecs::World,
    actions: BTreeMap<String, Vec<u32>>,
    /// Kept alive so the pointer handed to the host stays valid.
    scene_ron: String,
}}

static GAME: Mutex<Option<Game>> = Mutex::new(None);

fn parse<T: serde::de::DeserializeOwned + Default>(v: &ron::Value) -> Option<T> {{
    v.clone().into_rust::<T>().ok()
}}

fn insert_from<T: hecs::Component>(world: &mut hecs::World, e: hecs::Entity, c: Option<T>) {{
    if let Some(c) = c {{
        let _ = world.insert_one(e, c);
    }}
}}

/// Publish a mutated component back into its scene node, so the host sees live
/// state and Ctrl+S saves it.
fn write_back<T: serde::Serialize>(node: &mut scene::Node, name: &str, value: &T) {{
    if let Ok(text) = ron::to_string(value) {{
        if let Ok(v) = ron::from_str::<ron::Value>(&text) {{
            node.components.insert(name.to_string(), v);
        }}
    }}
}}

fn build_world(scene: &scene::Scene) -> hecs::World {{
    let mut world = hecs::World::new();
    for (i, node) in scene.nodes.iter().enumerate() {{
        let e = world.spawn((NodeIdx(i),));
        if let Some(c) = node.collider {{
            let _ = world.insert_one(e, c);
        }}
        for (name, value) in &node.components {{
            match name.as_str() {{
{component_arms}                _ => {{}}
            }}
        }}
    }}
    world
}}

/// AABB overlap in XY, from authored colliders only.
fn overlaps(
    a: (&scene::Transform, &scene::Collider),
    b: (&scene::Transform, &scene::Collider),
) -> bool {{
    let (ta, ca) = a;
    let (tb, cb) = b;
    (ta.translation[0] - tb.translation[0]).abs() < (ca.size[0] + cb.size[0]) * 0.5
        && (ta.translation[1] - tb.translation[1]).abs() < (ca.size[1] + cb.size[1]) * 0.5
}}

fn collision_pairs(game: &Game) -> Vec<(String, String)> {{
{overlap_blocks}}}

fn run_systems(game: &mut Game, dt: f32) {{
    let Game {{ scene, world, .. }} = game;
    let _ = (&scene, &world, dt);
{systems}}}

// ---------------------------------------------------------------- ABI

#[no_mangle]
pub extern "C" fn game_init(scene_ron: *const u8, len: u32) -> u32 {{
    let bytes = unsafe {{ std::slice::from_raw_parts(scene_ron, len as usize) }};
    let Ok(text) = std::str::from_utf8(bytes) else {{ return 1 }};
    let Ok(scene) = ron::from_str::<scene::Scene>(text) else {{ return 2 }};
    let Ok(map) = ron::from_str::<ActionMap>(ACTION_MAP) else {{ return 3 }};

    let actions = map
        .actions
        .into_iter()
        .map(|(name, binds)| (name, binds.iter().filter_map(|b| keys::code(b)).collect()))
        .collect();

    let world = build_world(&scene);
    *GAME.lock().unwrap() = Some(Game {{
        initial: scene.clone(),
        scene,
        world,
        actions,
        scene_ron: String::new(),
    }});
    0
}}

#[no_mangle]
pub extern "C" fn game_tick(dt: f32, keys_ptr: *const KeyFrame) -> u32 {{
    let mut guard = GAME.lock().unwrap();
    let Some(game) = guard.as_mut() else {{ return 1 }};
    let kf = unsafe {{ &*keys_ptr }};
    let held = unsafe {{ std::slice::from_raw_parts(kf.held, kf.held_len as usize) }};
    let pressed = unsafe {{ std::slice::from_raw_parts(kf.pressed, kf.pressed_len as usize) }};

    let resolve = |codes: &[u32]| -> std::collections::HashSet<String> {{
        game.actions
            .iter()
            .filter(|(_, binds)| binds.iter().any(|b| codes.contains(b)))
            .map(|(name, _)| name.clone())
            .collect()
    }};

    script::begin_frame(script::Frame {{
        held: resolve(held),
        pressed: resolve(pressed),
        overlaps: collision_pairs(game),
        restart_requested: false,
    }});

    run_systems(game, dt);

    if script::end_frame().restart_requested {{
        game.scene = game.initial.clone();
        game.world = build_world(&game.scene);
    }}
    0
}}

#[no_mangle]
pub extern "C" fn game_scene_ron(out_len: *mut u32) -> *const u8 {{
    let mut guard = GAME.lock().unwrap();
    let Some(game) = guard.as_mut() else {{
        unsafe {{ *out_len = 0 }};
        return std::ptr::null();
    }};
    game.scene_ron = ron::to_string(&game.scene).unwrap_or_default();
    unsafe {{ *out_len = game.scene_ron.len() as u32 }};
    game.scene_ron.as_ptr()
}}

#[no_mangle]
pub extern "C" fn game_restart() -> u32 {{
    let mut guard = GAME.lock().unwrap();
    let Some(game) = guard.as_mut() else {{ return 1 }};
    game.scene = game.initial.clone();
    game.world = build_world(&game.scene);
    0
}}
"#
    )
}
