//! Emits the crate that turns a game folder into a loadable module.
//!
//! A game folder holds only `scene.ron`, `input.tres.ron` and `.hom` files. The
//! ABI implementation, the World construction and the system dispatch are all
//! derived from what the `.hom` files declared, so a game never hand-writes
//! engine glue.

use crate::discover::{Module, Param};

/// One shared `engine` module means one `Transform` type for the whole crate,
/// which is why the modules are compiled with `--extern engine`.
pub fn cargo_toml(game: &str, engine_root: &str) -> String {
    format!(
        r#"# Generated by `shinra build`. Do not edit; regenerate instead.
[package]
name = "{game}"
version = "0.1.0"
edition = "2021"

[lib]
name = "{game}"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
shinra-engine = {{ path = "{engine_root}/engine" }}
scene         = {{ path = "{engine_root}/scene" }}
gametok-abi   = {{ path = "{engine_root}/abi" }}
hecs          = "0.10"
ron           = "0.10"
serde         = {{ version = "1", features = ["derive"] }}
"#
    )
}

fn component_arms(modules: &[Module]) -> String {
    let mut out = String::new();
    for m in modules {
        for c in &m.components {
            out.push_str(&format!(
                "            \"{c}\" => insert_from(&mut world, e, parse::<{module}::{c}>(name, value)),\n",
                module = m.name
            ));
        }
    }
    out
}

/// Which module declares a component, so a system's query can name its type.
fn owner_of<'a>(modules: &'a [Module], ty: &str) -> Option<&'a str> {
    modules
        .iter()
        .find(|m| m.components.iter().any(|c| c == ty))
        .map(|m| m.name.as_str())
}

fn system_block(m: &Module, sys: &crate::discover::System, modules: &[Module]) -> String {
    let comps: Vec<&Param> = sys
        .params
        .iter()
        .filter(|p| matches!(p, Param::Component { .. }))
        .collect();
    let wants_transform = sys.params.iter().any(|p| matches!(p, Param::Transform));

    // `&NodeIdx` is always in the query: a mutated component has to be written
    // back into the scene node it came from, or the host never sees it.
    let mut query_parts: Vec<String> = vec!["&NodeIdx".to_string()];
    for p in &comps {
        if let Param::Component { ty, by_ref } = p {
            let owner = owner_of(modules, ty).unwrap_or(&m.name);
            query_parts.push(if *by_ref {
                format!("&mut {owner}::{ty}")
            } else {
                format!("&{owner}::{ty}")
            });
        }
    }
    let query = format!("({})", query_parts.join(", "));

    let mut binds: Vec<String> = vec!["idx".to_string()];
    for (i, _) in comps.iter().enumerate() {
        binds.push(format!("c{i}"));
    }
    let bind_pat = format!("({})", binds.join(", "));

    // Call arguments, in declared parameter order.
    let mut ci = 0usize;
    let mut args: Vec<String> = Vec::new();
    for p in &sys.params {
        match p {
            Param::Transform => args.push("&mut node.transform".to_string()),
            Param::Dt => args.push("dt".to_string()),
            Param::Component { by_ref, .. } => {
                args.push(if *by_ref {
                    format!("c{ci}")
                } else {
                    format!("c{ci}.clone()")
                });
                ci += 1;
            }
        }
    }
    let call = format!("{}::{}({})", m.name, sys.name, args.join(", "));

    // The script indexes `[f32; 3]` directly, so the node's own transform is
    // handed over with no conversion.
    let _ = wants_transform;

    // Write mutated components back, so scene.ron reflects live state and the
    // host can read it.
    let mut write_back = String::new();
    let mut ci = 0usize;
    for p in &comps {
        if let Param::Component { ty, by_ref } = p {
            if *by_ref {
                write_back.push_str(&format!(
                    "        write_back(node, \"{ty}\", &*c{ci});\n"
                ));
            }
            ci += 1;
        }
    }

    format!(
        r#"    // {module}.hom
    for (_e, {bind_pat}) in world.query::<{query}>().iter() {{
        let node = &mut flat[idx.0].node;
        {call};
{write_back}    }}
"#,
        module = m.name
    )
}

fn contact_blocks(modules: &[Module]) -> String {
    let mut pairs: Vec<(String, String)> = Vec::new();
    for m in modules {
        for p in &m.overlap_pairs {
            if !pairs.contains(p) {
                pairs.push(p.clone());
            }
        }
    }
    if pairs.is_empty() {
        return "    Vec::new()\n".to_string();
    }
    let mut out = String::from("    let mut out = Vec::new();\n");
    for (a, b) in pairs {
        let (oa, ob) = (
            owner_of(modules, &a).unwrap_or(""),
            owner_of(modules, &b).unwrap_or(""),
        );
        if oa.is_empty() || ob.is_empty() {
            continue;
        }
        out.push_str(&format!(
            r#"    for (ea, ca) in game.world.query::<&scene::Collider>().iter() {{
        if game.world.get::<&{oa}::{a}>(ea).is_err() {{ continue }}
        let Ok(ia) = game.world.get::<&NodeIdx>(ea) else {{ continue }};
        let na = &game.flat[ia.0].node;
        let pa = placed(&game.flat, ia.0, *ca);
        for (eb, cb) in game.world.query::<&scene::Collider>().iter() {{
            if ea == eb {{ continue }}
            if game.world.get::<&{ob}::{b}>(eb).is_err() {{ continue }}
            let Ok(ib) = game.world.get::<&NodeIdx>(eb) else {{ continue }};
            let nb = &game.flat[ib.0].node;
            if let Some(h) = collide::hit(&pa, &placed(&game.flat, ib.0, *cb)) {{
                out.push(script::HitRecord {{
                    a_component: "{a}".to_string(),
                    b_component: "{b}".to_string(),
                    a_node: na.name.clone(),
                    b_node: nb.name.clone(),
                    normal: h.normal,
                    depth: h.depth,
                }});
            }}
        }}
    }}
"#
        ));
    }
    out.push_str("    out\n");
    out
}

pub fn lib_rs(game: &str, modules: &[Module]) -> String {
    let mod_decls: String = modules
        .iter()
        .map(|m| {
            format!(
                "#[allow(unused_variables, unused_mut, dead_code, unused_imports, unused_macros, non_snake_case)]\nmod {};\n",
                m.name
            )
        })
        .collect();

    // A module that queries contacts runs after they are recomputed, so a
    // response sees this tick's positions rather than last tick's.
    let movement: String = modules
        .iter()
        .filter(|m| m.overlap_pairs.is_empty())
        .flat_map(|m| m.systems.iter().map(move |s| system_block(m, s, modules)))
        .collect();
    let response: String = modules
        .iter()
        .filter(|m| !m.overlap_pairs.is_empty())
        .flat_map(|m| m.systems.iter().map(move |s| system_block(m, s, modules)))
        .collect();

    let component_arms = component_arms(modules);
    let contact_blocks = contact_blocks(modules);

    format!(
        r#"//! Generated by `shinra build` for the game `{game}`. Do not edit.
//!
//! The engine derives this from what the game's `.hom` files declared: each
//! `pub struct` is a component, and each `*_system` function's parameter list
//! is its query.

use std::collections::BTreeMap;
use std::sync::Mutex;

use gametok_abi::{{keys, KeyFrame}};
use shinra_engine::{{collide, script}};

/// The Homun runtime, once. `#[macro_use]` so its macros reach the modules
/// below, which import its traits via `--runtime-path super::runtime`.
#[macro_use]
#[allow(unused_variables, unused_mut, dead_code, unused_imports, unused_macros, non_snake_case)]
mod runtime {{
    include!("runtime.rs");
}}

/// The engine's Homun shim, once, so every module shares one `Transform`.
#[allow(unused_variables, unused_mut, dead_code, unused_imports, non_snake_case)]
mod engine;

{mod_decls}
const ACTION_MAP: &str = include_str!("input.tres.ron");

#[derive(serde::Deserialize)]
struct ActionMap {{
    actions: BTreeMap<String, Vec<String>>,
    #[serde(default)]
    axes: BTreeMap<String, AxisMap>,
}}

#[derive(serde::Deserialize)]
struct AxisMap {{
    #[serde(default)]
    neg: Vec<String>,
    #[serde(default)]
    pos: Vec<String>,
}}

/// Links an entity back to the flat node it is.
struct NodeIdx(usize);
/// Hierarchy, as an index into the flat list. Absent on a root.
struct ParentIdx(usize);
/// Position among a parent's children, so a save is stable.
struct SiblingIndex(u32);

struct Game {{
    /// The world, flat: an entity is one row and hierarchy is a component.
    flat: Vec<scene::FlatNode>,
    initial: Vec<scene::FlatNode>,
    /// The world's name, for the tree handed back to the host.
    name: String,
    world: hecs::World,
    actions: BTreeMap<String, Vec<u32>>,
    /// Axis name to (negative keys, positive keys).
    axes: BTreeMap<String, (Vec<u32>, Vec<u32>)>,
    /// Kept alive so the pointer handed to the host stays valid.
    scene_ron: String,
}}

static GAME: Mutex<Option<Game>> = Mutex::new(None);

/// Deserialize one game component out of the scene.
///
/// A marker component with no fields is naturally written `()`, which RON reads
/// as a unit rather than an empty struct, so that case takes the default. A
/// value that does not fit its type is reported: dropping it silently makes a
/// component simply never appear, which is very hard to see.
fn parse<T: serde::de::DeserializeOwned + Default>(name: &str, v: &ron::Value) -> Option<T> {{
    if matches!(v, ron::Value::Unit) {{
        return Some(T::default());
    }}
    match v.clone().into_rust::<T>() {{
        Ok(c) => Some(c),
        Err(e) => {{
            eprintln!("[{game}] component `{{name}}` does not fit its type: {{e}}");
            None
        }}
    }}
}}

fn insert_from<T: hecs::Component>(world: &mut hecs::World, e: hecs::Entity, c: Option<T>) {{
    if let Some(c) = c {{
        let _ = world.insert_one(e, c);
    }}
}}

/// Publish a mutated component back into its scene node, so the host sees live
/// state and Ctrl+S saves it.
fn write_back<T: serde::Serialize>(node: &mut scene::Node, name: &str, value: &T) {{
    if let Ok(text) = ron::to_string(value) {{
        if let Ok(v) = ron::from_str::<ron::Value>(&text) {{
            node.components.insert(name.to_string(), v);
        }}
    }}
}}

fn build_world(flat: &[scene::FlatNode]) -> hecs::World {{
    let mut world = hecs::World::new();
    for (i, f) in flat.iter().enumerate() {{
        let e = world.spawn((NodeIdx(i), SiblingIndex(f.sibling)));
        if let Some(p) = f.parent {{
            let _ = world.insert_one(e, ParentIdx(p));
        }}
        if let Some(c) = f.node.collider {{
            let _ = world.insert_one(e, c);
        }}
        for (name, value) in &f.node.components {{
            match name.as_str() {{
{component_arms}                _ => {{}}
            }}
        }}
    }}
    world
}}

/// AABB overlap in XY, from authored colliders only.
/// Place a collider in the XY plane for the engine's detector.
///
/// Uses the node's global transform: a collider on a child belongs where the
/// child actually is, not where its local transform says.
fn placed(flat: &[scene::FlatNode], index: usize, collider: scene::Collider) -> collide::Placed {{
    let g = scene::global_transform(flat, index);
    collide::Placed {{
        at: [g.translation[0], g.translation[1]],
        collider,
    }}
}}

/// Put the run back: restore every node's transform from the scene as loaded.
///
/// Components are left alone. A transform is where a thing is — that is the
/// run. A component is the game's own state, and whether a restart should clear
/// it is the game's rule, not the engine's: a score that survives a crash lives
/// in a component precisely because restart does not touch it.
fn restore_transforms(game: &mut Game) {{
    for (f, initial) in game.flat.iter_mut().zip(game.initial.iter()) {{
        f.node.transform = initial.node.transform;
    }}
}}

/// Contacts the game's systems asked about, from current positions.
fn contacts(game: &Game) -> Vec<script::HitRecord> {{
{contact_blocks}}}

/// Systems that move things. Contacts are stale during this phase.
fn run_movement(game: &mut Game, dt: f32) {{
    let Game {{ flat, world, .. }} = game;
    let _ = (&flat, &world, dt);
{movement}}}

/// Systems that respond to contacts, run after they were recomputed.
fn run_response(game: &mut Game, dt: f32) {{
    let Game {{ flat, world, .. }} = game;
    let _ = (&flat, &world, dt);
{response}}}

// ---------------------------------------------------------------- ABI

#[no_mangle]
pub extern "C" fn game_init(scene_ron: *const u8, len: u32) -> u32 {{
    let bytes = unsafe {{ std::slice::from_raw_parts(scene_ron, len as usize) }};
    let Ok(text) = std::str::from_utf8(bytes) else {{ return 1 }};
    let Ok(loaded) = ron::from_str::<scene::Scene>(text) else {{ return 2 }};
    let Ok(map) = ron::from_str::<ActionMap>(ACTION_MAP) else {{ return 3 }};

    let codes = |names: &[String]| -> Vec<u32> {{
        names.iter().filter_map(|n| keys::code(n)).collect()
    }};
    let actions = map
        .actions
        .iter()
        .map(|(name, binds)| (name.clone(), codes(binds)))
        .collect();
    let axes = map
        .axes
        .iter()
        .map(|(name, ax)| (name.clone(), (codes(&ax.neg), codes(&ax.pos))))
        .collect();

    let flat = scene::flatten(&loaded.nodes);
    let world = build_world(&flat);
    *GAME.lock().unwrap() = Some(Game {{
        initial: flat.clone(),
        flat,
        name: loaded.name,
        world,
        actions,
        axes,
        scene_ron: String::new(),
    }});
    0
}}

#[no_mangle]
pub extern "C" fn game_tick(dt: f32, keys_ptr: *const KeyFrame) -> u32 {{
    let mut guard = GAME.lock().unwrap();
    let Some(game) = guard.as_mut() else {{ return 1 }};
    let kf = unsafe {{ &*keys_ptr }};
    let held = unsafe {{ std::slice::from_raw_parts(kf.held, kf.held_len as usize) }};
    let pressed = unsafe {{ std::slice::from_raw_parts(kf.pressed, kf.pressed_len as usize) }};

    let resolve = |codes: &[u32]| -> std::collections::HashSet<String> {{
        game.actions
            .iter()
            .filter(|(_, binds)| binds.iter().any(|b| codes.contains(b)))
            .map(|(name, _)| name.clone())
            .collect()
    }};

    let axes = game
        .axes
        .iter()
        .map(|(name, (neg, pos))| (name.clone(), script::resolve_axis(held, neg, pos)))
        .collect();

    // Movement first, with no contacts published: a system that needs them is
    // in the response phase by construction.
    script::begin_frame(script::Frame {{
        held: resolve(held),
        pressed: resolve(pressed),
        axes,
        overlaps: Vec::new(),
        restart_requested: false,
    }});
    run_movement(game, dt);
    let mut frame = script::end_frame();

    // Recompute contacts from the positions movement just produced, then let
    // the response systems see them.
    frame.overlaps = contacts(game);
    script::begin_frame(frame);
    run_response(game, dt);

    if script::end_frame().restart_requested {{
        restore_transforms(game);
    }}
    0
}}

#[no_mangle]
pub extern "C" fn game_scene_ron(out_len: *mut u32) -> *const u8 {{
    let mut guard = GAME.lock().unwrap();
    let Some(game) = guard.as_mut() else {{
        unsafe {{ *out_len = 0 }};
        return std::ptr::null();
    }};
    // The host wants a tree; the runtime keeps it flat.
    let tree = scene::Scene {{
        name: game.name.clone(),
        nodes: scene::unflatten(&game.flat),
    }};
    game.scene_ron = ron::to_string(&tree).unwrap_or_default();
    unsafe {{ *out_len = game.scene_ron.len() as u32 }};
    game.scene_ron.as_ptr()
}}

/// A full reload, for the host: everything back to the scene as loaded,
/// components included.
#[no_mangle]
pub extern "C" fn game_restart() -> u32 {{
    let mut guard = GAME.lock().unwrap();
    let Some(game) = guard.as_mut() else {{ return 1 }};
    game.flat = game.initial.clone();
    game.world = build_world(&game.flat);
    0
}}
"#
    )
}
